name: Generate Code Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and generate code coverage report
      run: |
        pwsh ./GenerateCodeCoverage.ps1

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: Common.Shared/CodeCoverage