namespace Business.Domain.Services.RepositoryStatistics.GetOrgRepoCleanedCommits;

public interface IGetOrgRepoCleanedCommitsDomainService
{
  public Task<GetOrgRepoCleanedCommitsDomainResponse> GetCleanedCommits(GetOrgRepoCleanedCommitsDomainRequest domainRequest);
}