name: Generate Code Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up .NET
      uses: actions/setup-dotnet@v4.3.0
      with:
        dotnet-version: '8.0.x'

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Restore dependencies
      run: |
        dotnet workload restore
        dotnet restore

    - name: Run tests and generate code coverage report
      run: |
        pwsh ./GenerateCodeCoverage.ps1

    - name: Create branch for code coverage report
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b update-code-coverage
        git add Common.Shared/CodeCoverage
        git commit -m "Update code coverage report"
        git push --set-upstream origin update-code-coverage
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        commit-message: "Update code coverage report"
        branch: update-code-coverage
        title: "Update code coverage report"
        body: "This PR updates the code coverage report."
        base: main