name: Generate Code Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Run the workflow manually'
        default: 'true'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Execute coverlet code coverage and generate report
      run: |
        pwsh ./generateTestCoverage.ps1
        echo "Running PowerShell script"
